# exceptionally reinstate python 3.7 support, to be removed
# at any time, but ideally once upstream drops support itself
python:
  - 3.7.* *_cpython
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.14.* *_cp314
python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20
  - 1.21
  - 1.21
  - 1.21
  - 1.23
  - 1.26
  - 2.*
  - 2.*
