{% set name = "hll" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/HLL-{{ version }}.tar.gz
  sha256: 2000078723360d73c1d42061c55dc1e5b92df78e69a1be57ba868b9485e9853d

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - make
    - pip
  run:
    - python

test:
  imports:
    - HLL
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ascv/HyperLogLog
  summary: HyperLogLog implementation in C for python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
