{% set name = "hll" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82961d77c53d5628b553bb480428a3b685e8261f4350ad631916422b2bb75580

build:
  skip: true  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - make
    - pip
  run:
    - python

test:
  imports:
    - HLL
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ascv/HyperLogLog
  summary: HyperLogLog implementation in C for python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
