{% set name = "hll" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3805937c321606eb02a26e061297209978c05845fd5215b9cdcf2a5ac57a4be4

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - make
    - pip
  run:
    - python

test:
  imports:
    - HLL
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ascv/HyperLogLog
  summary: HyperLogLog implementation in C for python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
